name: homeworkout_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  permission_handler: ^8.2.6
  intl: ^0.17.0
  flutter_local_notifications: ^9.1.2
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.2
  charts_flutter: ^0.12.0
  share: ^2.0.4
  url_launcher: ^6.0.9
  auto_size_text: 3.0.0-nullsafety.0
  rate_my_app: ^1.1.1
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  group_radio_button: ^1.1.0
  open_settings: ^2.0.2
  android_intent_plus: ^3.0.2
  flutter_tts: ^3.2.2
  flutter_rounded_date_picker: ^2.0.2
  dotted_border: ^2.0.0+1
  align_positioned: ^2.0.4
  table_calendar: ^3.0.2
  date_format: ^2.0.4
  flutter_picker: ^2.0.2
  circular_countdown_timer: ^0.2.0
  audioplayers: ^0.20.1
  youtube_player_flutter: ^8.0.0
  lottie: ^1.2.1
  syncfusion_flutter_gauges: ^19.3.56
  percent_indicator: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/database/HomeWorkoutFlutter.db
    - assets/icons/
    - assets/icons/ic_select_pointer.webp
    - assets/icons/ic_challenge_complete_day.png
    - assets/icons/ic_menu.png
    - assets/icons/ic_menu_library.png
    - assets/icons/ic_menu_reminder.webp
    - assets/icons/ic_menu_report.png
    - assets/icons/ic_menu_restart_progress.webp
    - assets/icons/ic_menu_setting.webp
    - assets/icons/ic_training_plan.webp
    - assets/icons/ic_setting_coach_tips.webp
    - assets/icons/ic_setting_countdown_time.png
    - assets/icons/ic_setting_device_tts_setting.png
    - assets/icons/ic_setting_download_more_tts_langu.png
    - assets/icons/ic_setting_download_tts_engine.png
    - assets/icons/ic_setting_feedback.png
    - assets/icons/ic_setting_health_data.png
    - assets/icons/ic_setting_keep__screen.png
    - assets/icons/ic_setting_lang.webp
    - assets/icons/ic_setting_metric.png
    - assets/icons/ic_setting_navigat_pre.png
    - assets/icons/ic_setting_navigat_right.png
    - assets/icons/ic_setting_privacy_policy.png
    - assets/icons/ic_setting_rate_us.webp
    - assets/icons/ic_setting_reminder.webp
    - assets/icons/ic_setting_rest_set.png
    - assets/icons/ic_setting_sec_arrow.png
    - assets/icons/ic_setting_share.png
    - assets/icons/ic_setting_test_voice.webp
    - assets/icons/ic_setting_tts_engine.webp
    - assets/icons/ic_setting_voice_guide.webp
    - assets/icons/ic_sound_options.png
    - assets/icons/ic_back.webp
    - assets/icons/ic_edit.webp
    - assets/icons/drawer/
    - assets/icons/drawer/ic_discover_selected.webp
    - assets/icons/drawer/ic_discover_unselected.webp
    - assets/icons/drawer/ic_reminder_selected.webp
    - assets/icons/drawer/ic_reminder_unselected.webp
    - assets/icons/drawer/ic_report_selected.webp
    - assets/icons/drawer/ic_report_unselected.webp
    - assets/icons/drawer/ic_reset_progress.webp
    - assets/icons/drawer/ic_setting_selected.webp
    - assets/icons/drawer/ic_setting_unselected.webp
    - assets/icons/drawer/ic_training_selected.webp
    - assets/icons/drawer/ic_training_unselected.webp
    - assets/icons/cp_ic_animation.png
    - assets/images/
    - assets/images/main_bg.webp
    - assets/images/arm_intermediate.webp
    - assets/images/bg_set_week_goal.webp
    - assets/images/ic_challenge_uncomplete.webp
    - assets/images/ic_challenge_complete.png
    - assets/images/bg_libray.webp
    - assets/images/abs_advanced.webp
    - assets/images/men_banner.webp
    - assets/images/img_exercise.webp
    - assets/images/drawer_img.webp
    - assets/images/plan_ready.webp
    - assets/exerciseImage/discover/sleep/
    - assets/exerciseImage/discover/sleep/back_streching.webp
    - assets/exerciseImage/discover/sleep/lower_back_pain_relief.webp
    - assets/exerciseImage/discover/sleep/knee_pain_relief.jpg
    - assets/exerciseImage/discover/sleep/sleepy_time_stretching.webp
    - assets/exerciseImage/discover/sleep/shoulder_tension_relief.webp
    - assets/exerciseImage/discover/sleep/lower_body_stretching.webp
    - assets/exerciseImage/discover/sleep/upper_body_stretcing.webp
    - assets/exerciseImage/discover/sleep/neck_shoulder_tension_relief.webp
    - assets/exerciseImage/discover/sleep/morning_warm_up.webp
    - assets/exerciseImage/discover/sleep/full_body_stretching.webp
    - assets/exerciseImage/discover/equipment/
    - assets/exerciseImage/discover/equipment/with_equipment.webp
    - assets/exerciseImage/discover/fastWorkout/
    - assets/exerciseImage/discover/fastWorkout/7_min_abs_workout.webp
    - assets/exerciseImage/discover/fastWorkout/7_min_hiit_fat_burning.webp
    - assets/exerciseImage/discover/fastWorkout/7_min_classic.webp
    - assets/exerciseImage/discover/fastWorkout/before_workout_warmup.webp
    - assets/exerciseImage/discover/fastWorkout/3_exercises_lose_belly_fat.webp
    - assets/exerciseImage/discover/fastWorkout/4_min_tabata.webp
    - assets/exerciseImage/discover/quarantine/
    - assets/exerciseImage/discover/quarantine/dumbbell_workout_home.webp
    - assets/exerciseImage/discover/quarantine/band_workout_home.webp
    - assets/exerciseImage/discover/quarantine/stay_shape_women.webp
    - assets/exerciseImage/discover/quarantine/athletes_choice_home.webp
    - assets/exerciseImage/discover/quarantine/immunity_booster_home.webp
    - assets/exerciseImage/discover/picksForYou/
    - assets/exerciseImage/discover/picksForYou/fat_burning_hiit.webp
    - assets/exerciseImage/discover/picksForYou/hiit_intermediate.webp
    - assets/exerciseImage/discover/picksForYou/build_wider_shoulder.webp
    - assets/exerciseImage/discover/picksForYou/ripped_vcut_abs_sculpting.webp
    - assets/exerciseImage/discover/picksForYou/last_longer_in_bed.webp
    - assets/exerciseImage/discover/picksForYou/hiit_killer_core.webp
    - assets/exerciseImage/discover/picksForYou/get_rid of man_boobs_hiit.webp
    - assets/exerciseImage/discover/picksForYou/lose_fat_no_jump.webp
    - assets/exerciseImage/discover/picksForYou/belly_fat_burner_hiit.webp
    - assets/exerciseImage/intermediate/
    - assets/exerciseImage/intermediate/shoulder_back_intermediate_women.webp
    - assets/exerciseImage/intermediate/shoulder_back_intermediate_men.webp
    - assets/exerciseImage/intermediate/leg_intermediate_women.webp
    - assets/exerciseImage/intermediate/leg_intermediate_men.webp
    - assets/exerciseImage/intermediate/chest_intermediate_men.webp
    - assets/exerciseImage/intermediate/chest_intermediate_women.webp
    - assets/exerciseImage/intermediate/arm_intermediate_women.webp
    - assets/exerciseImage/intermediate/arm_intermediate_men.webp
    - assets/exerciseImage/intermediate/abs_intermediate_women.webp
    - assets/exerciseImage/intermediate/abs_intermediate_men.webp
    - assets/exerciseImage/advance/
    - assets/exerciseImage/advance/shoulder_back_advanced_women.webp
    - assets/exerciseImage/advance/shoulder_back_advanced_men.webp
    - assets/exerciseImage/advance/leg_advanced_women.webp
    - assets/exerciseImage/advance/leg_advanced_men.webp
    - assets/exerciseImage/advance/chest_advanced_women.webp
    - assets/exerciseImage/advance/arm_advanced_men.webp
    - assets/exerciseImage/advance/arm_advanced_women.webp
    - assets/exerciseImage/advance/abs_advanced_women.webp
    - assets/exerciseImage/advance/abs_advanced_men.webp
    - assets/exerciseImage/beginner/
    - assets/exerciseImage/beginner/shoulder_back_beginner_women.webp
    - assets/exerciseImage/beginner/shoulder_back_beginner_men.webp
    - assets/exerciseImage/beginner/leg_beginner_women.webp
    - assets/exerciseImage/beginner/leg_beginner_men.webp
    - assets/exerciseImage/beginner/chest_beginner_women.webp
    - assets/exerciseImage/beginner/abs_beginner_women.webp
    - assets/exerciseImage/beginner/abs_beginner_men.webp
    - assets/exerciseImage/other/
    - assets/exerciseImage/other/ic_six_pack.webp
    - assets/exerciseImage/other/ic_butt_leg.webp
    - assets/exerciseImage/other/ic_arm_shoulder.webp
    - assets/exerciseImage/other/ic_chest.webp
    - assets/exerciseImage/other/ic_burn_100_calories.webp
    - assets/exerciseImage/other/ic_20_min_body.webp
    - assets/exerciseImage/other/ic_belly_fat_burner.webp
    - assets/exerciseImage/other/ic_build_wider_shoulder_challenge.webp
    - assets/exerciseImage/other/ic_brutal_ladder_hiit.webp
    - assets/exerciseImage/other/ic_hiit_killer_core.webp
    - assets/exerciseImage/other/ic_killer_chest_workout.webp
    - assets/exerciseImage/other/ic_plank_challenge.webp
    - assets/exerciseImage/other/ic_beginner_core_workout.webp
    - assets/exerciseImage/other/ic_beginner_push_up.webp
    - assets/exerciseImage/other/ic_build_wider_shoulder_beginner.webp
    - assets/exerciseImage/other/ic_abs_workout_no_crumch.webp
    - assets/exerciseImage/other/ic_arm_workout_no_push_ups.webp
    - assets/exerciseImage/other/ic_leg_workout_no_jumping.webp
    - assets/exerciseImage/other/ic_only_4_moves_for_abs.webp
    - assets/exerciseImage/other/lower_body_women.webp
    - assets/exerciseImage/other/lower_body_men.webp
    - assets/exerciseImage/other/full_body_men.webp
    - assets/exerciseImage/other/full_body_women.webp
    - assets/exerciseImage/other/best_quarantine_men.webp
    - assets/exerciseImage/other/best_quarantine_women.webp
    - assets/animations/
    - assets/animations/congrats1.json
    - assets/animations/congrats2.json
    - assets/animations/congrats3.json
    - assets/sounds/whistle.wav


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
